// Mocks generated by Mockito 5.1.0 from annotations
// in lightning_api/test/lightning_api_client_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;
import 'dart:convert' as _i8;
import 'dart:typed_data' as _i9;

import 'package:http/http.dart' as _i6;
import 'package:http/src/base_request.dart' as _i10;
import 'package:http/src/response.dart' as _i2;
import 'package:http/src/streamed_response.dart' as _i3;
import 'package:lightning_api/lightning_api.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rxdart/streams.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeResponse_0 extends _i1.Fake implements _i2.Response {}

class _FakeStreamedResponse_1 extends _i1.Fake implements _i3.StreamedResponse {
}

class _FakeValueStream_2<T> extends _i1.Fake implements _i4.ValueStream<T> {}

class _FakeSearchResults_3 extends _i1.Fake implements _i5.SearchResults {}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i6.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i2.Response>.value(_FakeResponse_0()))
          as _i7.Future<_i2.Response>);
  @override
  _i7.Future<_i2.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i2.Response>.value(_FakeResponse_0()))
          as _i7.Future<_i2.Response>);
  @override
  _i7.Future<_i2.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i8.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i2.Response>.value(_FakeResponse_0()))
          as _i7.Future<_i2.Response>);
  @override
  _i7.Future<_i2.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i8.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i2.Response>.value(_FakeResponse_0()))
          as _i7.Future<_i2.Response>);
  @override
  _i7.Future<_i2.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i8.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i2.Response>.value(_FakeResponse_0()))
          as _i7.Future<_i2.Response>);
  @override
  _i7.Future<_i2.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i8.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i2.Response>.value(_FakeResponse_0()))
          as _i7.Future<_i2.Response>);
  @override
  _i7.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  _i7.Future<_i9.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i9.Uint8List>.value(_i9.Uint8List(0)))
          as _i7.Future<_i9.Uint8List>);
  @override
  _i7.Future<_i3.StreamedResponse> send(_i10.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue:
                  Future<_i3.StreamedResponse>.value(_FakeStreamedResponse_1()))
          as _i7.Future<_i3.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
}

/// A class which mocks [Response].
///
/// See the documentation for Mockito's code generation for more information.
class MockResponse extends _i1.Mock implements _i2.Response {
  MockResponse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Uint8List get bodyBytes =>
      (super.noSuchMethod(Invocation.getter(#bodyBytes),
          returnValue: _i9.Uint8List(0)) as _i9.Uint8List);
  @override
  String get body =>
      (super.noSuchMethod(Invocation.getter(#body), returnValue: '') as String);
  @override
  int get statusCode =>
      (super.noSuchMethod(Invocation.getter(#statusCode), returnValue: 0)
          as int);
  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(Invocation.getter(#headers),
          returnValue: <String, String>{}) as Map<String, String>);
  @override
  bool get isRedirect =>
      (super.noSuchMethod(Invocation.getter(#isRedirect), returnValue: false)
          as bool);
  @override
  bool get persistentConnection =>
      (super.noSuchMethod(Invocation.getter(#persistentConnection),
          returnValue: false) as bool);
}

/// A class which mocks [LightningApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockLightningApiClient extends _i1.Mock
    implements _i5.LightningApiClient {
  MockLightningApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<_i5.Feed> getFeed({String? tag, _i5.FeedSortOrder? sort}) => (super
      .noSuchMethod(Invocation.method(#getFeed, [], {#tag: tag, #sort: sort}),
          returnValue: Stream<_i5.Feed>.empty()) as _i7.Stream<_i5.Feed>);
  @override
  void refreshFeed({String? tag, _i5.FeedSortOrder? sort}) =>
      super.noSuchMethod(
          Invocation.method(#refreshFeed, [], {#tag: tag, #sort: sort}),
          returnValueForMissingStub: null);
  @override
  void expandFeed({String? tag, _i5.FeedSortOrder? sort, int? amount = 20}) =>
      super.noSuchMethod(
          Invocation.method(
              #expandFeed, [], {#tag: tag, #sort: sort, #amount: amount}),
          returnValueForMissingStub: null);
  @override
  _i4.ValueStream<_i5.Post> getPost(_i5.Authorperm? id) =>
      (super.noSuchMethod(Invocation.method(#getPost, [id]),
              returnValue: _FakeValueStream_2<_i5.Post>())
          as _i4.ValueStream<_i5.Post>);
  @override
  _i7.Future<void> refreshPost(_i5.Authorperm? id) =>
      (super.noSuchMethod(Invocation.method(#refreshPost, [id]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i4.ValueStream<_i5.Comments> getComments(_i5.Authorperm? postId) =>
      (super.noSuchMethod(Invocation.method(#getComments, [postId]),
              returnValue: _FakeValueStream_2<_i5.Comments>())
          as _i4.ValueStream<_i5.Comments>);
  @override
  void refreshComments(_i5.Authorperm? id) =>
      super.noSuchMethod(Invocation.method(#refreshComments, [id]),
          returnValueForMissingStub: null);
  @override
  _i7.Future<_i5.SearchResults> search(String? query,
          {int? start, int? limit}) =>
      (super.noSuchMethod(
          Invocation.method(#search, [query], {#start: start, #limit: limit}),
          returnValue:
              Future<_i5.SearchResults>.value(_FakeSearchResults_3())) as _i7
          .Future<_i5.SearchResults>);
}
